#!/bin/sh

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/packages" && pwd)

if which -s scutil; then
    host=$(scutil --get ComputerName)
elif [ -f /etc/hostname ]; then
    host=$(cat /etc/hostname)
else
    echo "Uh oh, I don't know what hostname to use" >&2
    exit 1
fi

echo "-d $dir/" > ~/.stowrc
echo "-t $HOME/" >> ~/.stowrc
echo '-v' >> ~/.stowrc

if [ -d "$dir/system-$host" ]; then
    stow "system-$host"
fi

stow git vim zsh
