#!/bin/sh

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/packages" && pwd)

if [ "$(uname -s)" == "Darwin" ]; then
    host=$(scutil --get ComputerName)
else
    host=$(cat /etc/hostname)
fi

echo "-d $dir/" > ~/.stowrc
echo "-t $HOME/" >> ~/.stowrc
echo '-v' >> ~/.stowrc

if [ -d "$dir/system-$host" ]; then
    stow "system-$host"
fi

stow git vim zsh

