#!/bin/sh

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/packages" && pwd)

if [ "$(uname -s)" == "Darwin" ]; then
    host=$(scutil --get ComputerName)
else
    host=$(cat /etc/hostname)
fi

echo $host

echo "-d $dir/" > ~/.stowrc
echo "-t $HOME/" >> ~/.stowrc
echo '-v' >> ~/.stowrc

if [ -d "$dir/system-$host" ]; then
    echo "hello"
    stow "system-$host"
fi

stow git vim zsh

case $host in
    abra)
        stow gradle haskell i3 rtorrent ruby xorg
        ;;
    poliwrath)
        stow ruby www
        ;;
esac

